### ISSUE TITLE
Install using nix

### ISSUE THREAD

**Issue by sweh** [wosc/git-persona#3]
Hi wosc,

maybe you can help me: I installed `git` with `nix` and I'm unsure how to install your extension now. Do you have a clue?

Thanks and best regards!

**Comment by wosc** [comment]
Hey, I'm sorry to say I know nothing about nix. My guess is, it should know how to install a python package? And put that on the same PATH as the `git` it also installed? But really: I know nothing about nix. Sorry.

**Comment by sweh** [comment]
Hi wosc,

just a note in case someone has the same mistake as me: `gitpersona` does not have to be installed in a Python environment in which `git` is also installed. That's what I assumed. I didn't realize that in your README you suggested installing the package with a global `pip`, but apparently that's the way. I always install global packages with `pipx`, and it works wonderfully for `ws.gitpersona`.

Cheers,
  Sebastian
